name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  backend-test:
    runs-on: ubuntu-latest

    steps:
      - name : Repository checkout
        uses: actions/checkout@v4

      - name: Java 11 setup      
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Backend project build
        working-directory: ./back
        run: mvn clean install

      - name: Backend test
        working-directory: ./back
        run: mvn test

      - name: Backend test results upload
        uses: actions/upload-artifact@v4
        with:
          name: backend-test-report
          path: ./back/target/site/jacoco/


  frontend-test:
    runs-on: ubuntu-latest

    steps:
    - name : Repository checkout
      uses: actions/checkout@v4
      
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
        cache-dependency-path: ./front/package-lock.json
        
    - name: Dependencies clean install
      working-directory: ./front
      run: npm ci
      
    - name: Frontend project build
      working-directory: ./front
      run: npm run build --if-present
      
    - name: Frontend test
      working-directory: ./front
      run: npm test -- --browsers=ChromeHeadless --watch=false --code-coverage
      
    - name: Frontend test results upload
      uses: actions/upload-artifact@v4
      with:
        name: frontend-test-report
        path: ./front/coverage/bobapp/

  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
