name: Test workflow

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  backend-test:
    runs-on: ubuntu-latest

    steps:
      - name : Repository checkout
        uses: actions/checkout@v4

      - name: Java 11 setup      
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Backend project build
        working-directory: ./back
        run: mvn clean install

      - name: Backend test
        working-directory: ./back
        run: mvn test

      - name: Backend test results upload
        uses: actions/upload-artifact@v4
        with:
          name: backend-test-report
          path: ./back/target/site/jacoco/


  frontend-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - name : Repository checkout
      uses: actions/checkout@v4
      
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'
        cache: 'npm'
        
    - name: Dependencies clean install
      run: npm ci
      
    - name: Frontend project build
      run: npm run build --if-present
      
    - name: Frontend test
      run: npm test
      
    - name: Frontend test results upload
      uses: actions/upload-artifact@v4
      with:
        name: frontend-test-report
        path: ./front/coverage/bobapp/
